config/routes.rb
NatalFeliz::Application.routes.draw do
  root 'campaigns#index'

  resources :campanhas, controller: 'campaigns'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :places
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :campaign
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_campaign, except: [:index, :create, :new]

  def index
    @campanhas = Campaign.includes('places').all

    respond_to do |format|
      format.html { render layout: false }
      format.json { render json: @campanhas.to_json(include: :places)}
    end
  end

  def show
  end

  def create
  end

  private
    attr_reader :campaign

    def permitted_params
      params.require(:campaign).permit(:name, :description, { :places => [ :name, :address ]})
    end

    def set_campaign
      @campaign = Campaign.find params[:id]
    end

    def authenticate_user!
      redirect_to :root unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/index.html.erb
<!doctype html>
<html class="no-js">
  <head>
    <title>Campanhas do bem</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "home.css" %>

    <script src="assets/modernizr.js"></script>

    <style type="text/css">
      #map-canvas {
        height: 100%;
      }
    </style>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZC20RoWDFSS6WvTNwqWNaiJkmvZ5qYy0&sensor=true"></script>

  </head>
  <body>
    <div class="wrapper">
      <div class="navbar navbar-default navbar-fixed-top navbar-horizontal-custom">
        <div class="container">
          <div class="navbar-header">
            <a href="../" class="navbar-brand">Campanhas do bem</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#"><span class="icon-wrapper"><i class="fa fa-facebook"></i></span>facebook</a></li>
                  <li><a href="#"><span class="icon-wrapper"><i class="fa fa-twitter"></i></span>twiter</a></li>
                </ul>
              </li>
              <li>
                <%= link_to "Criar campanha", new_campanha_path %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="navbar-vertical navbar-default">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">
            <img src="assets/logo.png" width="130px" />
          </a>
          <h1>Campanhas do bem</h1>
          <aside>
            Encontre doações espalhadas pelo Brasil.
          </aside>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <span>Olá <strong><%= current_user.name %></strong>!</span>
                <%= link_to "Sair", signout_path, id: "sign_out" %>
              </li>
              <li>
                <%= link_to "Criar campanha", new_campanha_path %>
              </li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to("/auth/facebook") do %>
                      <span class="icon-wrapper"><i class="fa fa-facebook"></i></span>facebook</a>
                  <% end %>
                </li>
                <li>
                  <%= link_to("/auth/twitter") do %>
                    <span class="icon-wrapper"><i class="fa fa-twitter"></i></span>twitter</a>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="offset map-container">
    <div id="map-canvas"></div>
  </div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46474265-1', 'campanhadobem.com.br');
  ga('send', 'pageview');
</script>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= javascript_include_tag "maps.js" %>
<%= javascript_include_tag "home.js" %>

<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

    <script type="text/template" id="infoWindowTemplate">
        <div>
            <h4>{{TITLE}}</h4>
            <p data-description="description">{{DESCRIPTION}}</p>
            <b>Ponto de coleta</b><br />
            <b>{{ADDRESSNAME}}</b><br />
            <p>{{ADDRESS}}</p>
            <a href="{{LINK}}" class="btn btn-success share">Compartilhar</a>
        </div>
    </script>
</body>
    </html>

app/views/campaigns/new.html.erb
<div class="col-xs-12 col-md-4 full-height">
  <div class="container">
    <h1 id="navbar">Informações</h1>
    <div class="col-xs-12 col-md-4 full-height">
      <form role="form" id="view" data-bind="submit: sendForm">
        <!-- ko with: campaign -->
        <div class="form-group">
          <label for="nome">Nome</label>
          <input type="text" class="form-control" name="nome" placeholder="Brinquedos para as crianças" data-bind="value: name">
        </div>
        <div class="form-group">
          <label for="descricao">Descrição</label>
          <span class="help-block">Informe aqui para onde serão destinadas as doações, o que estão arrecadando, etc...</span>
          <textarea class="form-control" rows="6" name="descricao" data-bind="value: description"></textarea>
        </div>
        <!-- /ko -->

        <button type="submit" class="btn btn-success">Criar campanha</button>
      </form>
    </div>
  </div>
</div>
<div class="col-xs-12 col-md-8 sidebar-offcanvas full-height">
  <div class="container-fluid">
    <h1 id="navbar">Pontos de Coleta</h1>
    <span class="help-block">Clique no local desejado para adicionar um ponto de coleta.</span>
    <div class="col-xs-12 col-md-12 col-for-map">
      <div class="map-container">
        <div id="map-canvas"></div>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="map-container">
	<div id="map-canvas"></div>
</div>

<script type="text/template" id="infoWindowTemplate">
	<div>
		<h4>{{TITLE}}</h4>
		<p>{{DESCRIPTION}}</p>
		<b>Ponto de coleta</b><br />
		<b>{{ADDRESSNAME}}</b><br />
		<p>{{ADDRESS}}</p>
		<a href="{{LINK}}" class="btn btn-success">Compartilhar</a>
	</div>
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Campanhas do bem</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <script src="/assets/modernizr.js"></script>

    <style type="text/css">
      #map-canvas {
        height: 100%;
      }
    </style>

    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZC20RoWDFSS6WvTNwqWNaiJkmvZ5qYy0&sensor=true">
      </script>
    </head>
    <body>
      <div class="wrapper">
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <% if @campaign && @campaign.name %>
                <a href="../" class="navbar-brand"><%= @campaign.name %></a>
              <% else %>
                <a href="/" class="navbar-brand">Campanhas do bem</a>
              <% end %>
              <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
              <ul class="nav navbar-nav navbar-right">
                <% unless current_user %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="#"><span class="icon-wrapper"><i class="fa fa-facebook"></i></span>facebook</a></li>
                      <li><a href="#"><span class="icon-wrapper"><i class="fa fa-twitter"></i></span>twiter</a></li>
                    </ul>
                  </li>
                <% else %>
                  <li>
                    Olá <%= current_user.name %>
                </li>
              <% end %>
              <li>
                <%= link_to "Criar campanha", new_campanha_path %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div>
        <%= yield %>
      </div>
    </div>
  </div>

  <script type="text/html" id="coleta-template">
    <ul class="list-group" data-bind="foreach: campaign().places">
      <li class="list-group-item">
        <button class="badge">X</button>
        <!-- ko text: name -->
        <!-- /ko -->
      </li>
    </ul>
  </script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46474265-1', 'campanhadobem.com.br');
    ga('send', 'pageview');

  </script>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "maps.js" %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

  <script type="text/template" id="infoWindowTemplate">
    <div>
      <b>Ponto de coleta</b><br />
      <b>{{ADDRESSNAME}}</b><br />
      <p>{{ADDRESS}}</p>
      <button class="btn btn-danger  btn-sm removePlace" id="{{ID}}">remover</button>
    </div>
  </script>
</body>
</html>